/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IComplianceModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchVerifyUsers"
      | "blacklistUser"
      | "checkCompliance"
      | "checkTransactionLimits"
      | "deactivateUser"
      | "extendVerification"
      | "getAllVerifiedUsers"
      | "getUserById"
      | "getUserByPhone"
      | "getUserCompliance"
      | "getUserMonthlyLimit"
      | "getUserMonthlySpent"
      | "getUserTransactionLimit"
      | "getVerifiedUserCount"
      | "isUserBlacklisted"
      | "isUserVerified"
      | "pause"
      | "reactivateUser"
      | "removeFromBlacklist"
      | "reportSuspiciousActivity"
      | "unpause"
      | "updateComplianceLevel"
      | "verifyUser"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceLevelUpdated"
      | "SuspiciousActivityReported"
      | "TransactionLimitExceeded"
      | "UserBlacklisted"
      | "UserVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchVerifyUsers",
    values: [
      AddressLike[],
      string[],
      string[],
      string[],
      string[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistUser",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkCompliance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTransactionLimits",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extendVerification",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVerifiedUsers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getUserById", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getUserByPhone",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCompliance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMonthlyLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMonthlySpent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTransactionLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiedUserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUserBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportSuspiciousActivity",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateComplianceLevel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyUser",
    values: [AddressLike, string, string, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchVerifyUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTransactionLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllVerifiedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserByPhone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMonthlyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMonthlySpent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTransactionLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiedUserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportSuspiciousActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateComplianceLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyUser", data: BytesLike): Result;
}

export namespace ComplianceLevelUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    oldLevel: BigNumberish,
    newLevel: BigNumberish
  ];
  export type OutputTuple = [user: string, oldLevel: bigint, newLevel: bigint];
  export interface OutputObject {
    user: string;
    oldLevel: bigint;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuspiciousActivityReportedEvent {
  export type InputTuple = [
    user: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, reason: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionLimitExceededEvent {
  export type InputTuple = [
    user: AddressLike,
    attemptedAmount: BigNumberish,
    limit: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    attemptedAmount: bigint,
    limit: bigint
  ];
  export interface OutputObject {
    user: string;
    attemptedAmount: bigint;
    limit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserBlacklistedEvent {
  export type InputTuple = [
    user: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, reason: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserVerifiedEvent {
  export type InputTuple = [
    user: AddressLike,
    realName: string,
    level: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    realName: string,
    level: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    realName: string;
    level: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IComplianceModule extends BaseContract {
  connect(runner?: ContractRunner | null): IComplianceModule;
  waitForDeployment(): Promise<this>;

  interface: IComplianceModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchVerifyUsers: TypedContractMethod<
    [
      users: AddressLike[],
      realNames: string[],
      idNumbers: string[],
      phoneNumbers: string[],
      bankAccounts: string[],
      levels: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  blacklistUser: TypedContractMethod<
    [user: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  checkCompliance: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  checkTransactionLimits: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  deactivateUser: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  extendVerification: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  getAllVerifiedUsers: TypedContractMethod<[], [string[]], "view">;

  getUserById: TypedContractMethod<
    [identificationNumber: string],
    [string],
    "view"
  >;

  getUserByPhone: TypedContractMethod<[phoneNumber: string], [string], "view">;

  getUserCompliance: TypedContractMethod<
    [user: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        userAddress: string;
        realName: string;
        identificationNumber: string;
        phoneNumber: string;
        bankAccount: string;
        isVerified: boolean;
        isActive: boolean;
        verificationDate: bigint;
        lastUpdate: bigint;
        level: bigint;
        transactionLimit: bigint;
        monthlyLimit: bigint;
        monthlySpent: bigint;
        lastMonthReset: bigint;
      }
    ],
    "view"
  >;

  getUserMonthlyLimit: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserMonthlySpent: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserTransactionLimit: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getVerifiedUserCount: TypedContractMethod<[], [bigint], "view">;

  isUserBlacklisted: TypedContractMethod<
    [user: AddressLike],
    [boolean],
    "view"
  >;

  isUserVerified: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  reactivateUser: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  removeFromBlacklist: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  reportSuspiciousActivity: TypedContractMethod<
    [user: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateComplianceLevel: TypedContractMethod<
    [user: AddressLike, newLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyUser: TypedContractMethod<
    [
      user: AddressLike,
      realName: string,
      identificationNumber: string,
      phoneNumber: string,
      bankAccount: string,
      level: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchVerifyUsers"
  ): TypedContractMethod<
    [
      users: AddressLike[],
      realNames: string[],
      idNumbers: string[],
      phoneNumbers: string[],
      bankAccounts: string[],
      levels: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklistUser"
  ): TypedContractMethod<
    [user: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkCompliance"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkTransactionLimits"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateUser"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "extendVerification"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllVerifiedUsers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserById"
  ): TypedContractMethod<[identificationNumber: string], [string], "view">;
  getFunction(
    nameOrSignature: "getUserByPhone"
  ): TypedContractMethod<[phoneNumber: string], [string], "view">;
  getFunction(
    nameOrSignature: "getUserCompliance"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        userAddress: string;
        realName: string;
        identificationNumber: string;
        phoneNumber: string;
        bankAccount: string;
        isVerified: boolean;
        isActive: boolean;
        verificationDate: bigint;
        lastUpdate: bigint;
        level: bigint;
        transactionLimit: bigint;
        monthlyLimit: bigint;
        monthlySpent: bigint;
        lastMonthReset: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserMonthlyLimit"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserMonthlySpent"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserTransactionLimit"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVerifiedUserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isUserBlacklisted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isUserVerified"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reactivateUser"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeFromBlacklist"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportSuspiciousActivity"
  ): TypedContractMethod<
    [user: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateComplianceLevel"
  ): TypedContractMethod<
    [user: AddressLike, newLevel: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyUser"
  ): TypedContractMethod<
    [
      user: AddressLike,
      realName: string,
      identificationNumber: string,
      phoneNumber: string,
      bankAccount: string,
      level: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComplianceLevelUpdated"
  ): TypedContractEvent<
    ComplianceLevelUpdatedEvent.InputTuple,
    ComplianceLevelUpdatedEvent.OutputTuple,
    ComplianceLevelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SuspiciousActivityReported"
  ): TypedContractEvent<
    SuspiciousActivityReportedEvent.InputTuple,
    SuspiciousActivityReportedEvent.OutputTuple,
    SuspiciousActivityReportedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionLimitExceeded"
  ): TypedContractEvent<
    TransactionLimitExceededEvent.InputTuple,
    TransactionLimitExceededEvent.OutputTuple,
    TransactionLimitExceededEvent.OutputObject
  >;
  getEvent(
    key: "UserBlacklisted"
  ): TypedContractEvent<
    UserBlacklistedEvent.InputTuple,
    UserBlacklistedEvent.OutputTuple,
    UserBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "UserVerified"
  ): TypedContractEvent<
    UserVerifiedEvent.InputTuple,
    UserVerifiedEvent.OutputTuple,
    UserVerifiedEvent.OutputObject
  >;

  filters: {
    "ComplianceLevelUpdated(address,uint8,uint8)": TypedContractEvent<
      ComplianceLevelUpdatedEvent.InputTuple,
      ComplianceLevelUpdatedEvent.OutputTuple,
      ComplianceLevelUpdatedEvent.OutputObject
    >;
    ComplianceLevelUpdated: TypedContractEvent<
      ComplianceLevelUpdatedEvent.InputTuple,
      ComplianceLevelUpdatedEvent.OutputTuple,
      ComplianceLevelUpdatedEvent.OutputObject
    >;

    "SuspiciousActivityReported(address,string,uint256)": TypedContractEvent<
      SuspiciousActivityReportedEvent.InputTuple,
      SuspiciousActivityReportedEvent.OutputTuple,
      SuspiciousActivityReportedEvent.OutputObject
    >;
    SuspiciousActivityReported: TypedContractEvent<
      SuspiciousActivityReportedEvent.InputTuple,
      SuspiciousActivityReportedEvent.OutputTuple,
      SuspiciousActivityReportedEvent.OutputObject
    >;

    "TransactionLimitExceeded(address,uint256,uint256)": TypedContractEvent<
      TransactionLimitExceededEvent.InputTuple,
      TransactionLimitExceededEvent.OutputTuple,
      TransactionLimitExceededEvent.OutputObject
    >;
    TransactionLimitExceeded: TypedContractEvent<
      TransactionLimitExceededEvent.InputTuple,
      TransactionLimitExceededEvent.OutputTuple,
      TransactionLimitExceededEvent.OutputObject
    >;

    "UserBlacklisted(address,string,uint256)": TypedContractEvent<
      UserBlacklistedEvent.InputTuple,
      UserBlacklistedEvent.OutputTuple,
      UserBlacklistedEvent.OutputObject
    >;
    UserBlacklisted: TypedContractEvent<
      UserBlacklistedEvent.InputTuple,
      UserBlacklistedEvent.OutputTuple,
      UserBlacklistedEvent.OutputObject
    >;

    "UserVerified(address,string,uint8,uint256)": TypedContractEvent<
      UserVerifiedEvent.InputTuple,
      UserVerifiedEvent.OutputTuple,
      UserVerifiedEvent.OutputObject
    >;
    UserVerified: TypedContractEvent<
      UserVerifiedEvent.InputTuple,
      UserVerifiedEvent.OutputTuple,
      UserVerifiedEvent.OutputObject
    >;
  };
}
