/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IInvestmentPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDepositToPool"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "collectFees"
      | "distributeReturns"
      | "emergencyWithdraw"
      | "getDepositInvestors"
      | "getDepositPool"
      | "getTotalPoolStats"
      | "getUserInvestments"
      | "getUserSharesInDeposit"
      | "investInDeposit"
      | "pause"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "unpause"
      | "withdrawFromDeposit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "DepositAdded"
      | "FeesCollected"
      | "InvestmentMade"
      | "InvestmentWithdrawn"
      | "ReturnsDistributed"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDepositToPool",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReturns",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositInvestors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPoolStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInvestments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSharesInDeposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investInDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFromDeposit",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addDepositToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeReturns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPoolStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSharesInDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investInDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromDeposit",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositAddedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    amount: BigNumberish,
    expectedReturn: BigNumberish
  ];
  export type OutputTuple = [
    depositId: bigint,
    amount: bigint,
    expectedReturn: bigint
  ];
  export interface OutputObject {
    depositId: bigint;
    amount: bigint;
    expectedReturn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesCollectedEvent {
  export type InputTuple = [
    managementFees: BigNumberish,
    performanceFees: BigNumberish
  ];
  export type OutputTuple = [managementFees: bigint, performanceFees: bigint];
  export interface OutputObject {
    managementFees: bigint;
    performanceFees: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentMadeEvent {
  export type InputTuple = [
    investor: AddressLike,
    depositId: BigNumberish,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    depositId: bigint,
    amount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    investor: string;
    depositId: bigint;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentWithdrawnEvent {
  export type InputTuple = [
    investor: AddressLike,
    depositId: BigNumberish,
    amount: BigNumberish,
    profit: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    depositId: bigint,
    amount: bigint,
    profit: bigint
  ];
  export interface OutputObject {
    investor: string;
    depositId: bigint;
    amount: bigint;
    profit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReturnsDistributedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    totalReturns: BigNumberish
  ];
  export type OutputTuple = [depositId: bigint, totalReturns: bigint];
  export interface OutputObject {
    depositId: bigint;
    totalReturns: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IInvestmentPool extends BaseContract {
  connect(runner?: ContractRunner | null): IInvestmentPool;
  waitForDeployment(): Promise<this>;

  interface: IInvestmentPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDepositToPool: TypedContractMethod<
    [depositId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  collectFees: TypedContractMethod<[], [void], "nonpayable">;

  distributeReturns: TypedContractMethod<
    [depositId: BigNumberish, totalReturns: BigNumberish],
    [void],
    "payable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getDepositInvestors: TypedContractMethod<
    [depositId: BigNumberish],
    [string[]],
    "view"
  >;

  getDepositPool: TypedContractMethod<
    [depositId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalAmount: bigint;
        availableAmount: bigint;
        totalInvested: bigint;
        expectedReturn: bigint;
        actualReturn: bigint;
        startDate: bigint;
        endDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getTotalPoolStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalPoolValue: bigint;
        totalShares: bigint;
        totalInvestors: bigint;
      }
    ],
    "view"
  >;

  getUserInvestments: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserSharesInDeposit: TypedContractMethod<
    [user: AddressLike, depositId: BigNumberish],
    [bigint],
    "view"
  >;

  investInDeposit: TypedContractMethod<
    [depositId: BigNumberish],
    [void],
    "payable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawFromDeposit: TypedContractMethod<
    [depositId: BigNumberish, shareAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDepositToPool"
  ): TypedContractMethod<
    [depositId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeReturns"
  ): TypedContractMethod<
    [depositId: BigNumberish, totalReturns: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDepositInvestors"
  ): TypedContractMethod<[depositId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDepositPool"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalAmount: bigint;
        availableAmount: bigint;
        totalInvested: bigint;
        expectedReturn: bigint;
        actualReturn: bigint;
        startDate: bigint;
        endDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPoolStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalPoolValue: bigint;
        totalShares: bigint;
        totalInvestors: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserInvestments"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserSharesInDeposit"
  ): TypedContractMethod<
    [user: AddressLike, depositId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "investInDeposit"
  ): TypedContractMethod<[depositId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFromDeposit"
  ): TypedContractMethod<
    [depositId: BigNumberish, shareAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "DepositAdded"
  ): TypedContractEvent<
    DepositAddedEvent.InputTuple,
    DepositAddedEvent.OutputTuple,
    DepositAddedEvent.OutputObject
  >;
  getEvent(
    key: "FeesCollected"
  ): TypedContractEvent<
    FeesCollectedEvent.InputTuple,
    FeesCollectedEvent.OutputTuple,
    FeesCollectedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentMade"
  ): TypedContractEvent<
    InvestmentMadeEvent.InputTuple,
    InvestmentMadeEvent.OutputTuple,
    InvestmentMadeEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentWithdrawn"
  ): TypedContractEvent<
    InvestmentWithdrawnEvent.InputTuple,
    InvestmentWithdrawnEvent.OutputTuple,
    InvestmentWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ReturnsDistributed"
  ): TypedContractEvent<
    ReturnsDistributedEvent.InputTuple,
    ReturnsDistributedEvent.OutputTuple,
    ReturnsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "DepositAdded(uint256,uint256,uint256)": TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;
    DepositAdded: TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;

    "FeesCollected(uint256,uint256)": TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;
    FeesCollected: TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;

    "InvestmentMade(address,uint256,uint256,uint256)": TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;
    InvestmentMade: TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;

    "InvestmentWithdrawn(address,uint256,uint256,uint256)": TypedContractEvent<
      InvestmentWithdrawnEvent.InputTuple,
      InvestmentWithdrawnEvent.OutputTuple,
      InvestmentWithdrawnEvent.OutputObject
    >;
    InvestmentWithdrawn: TypedContractEvent<
      InvestmentWithdrawnEvent.InputTuple,
      InvestmentWithdrawnEvent.OutputTuple,
      InvestmentWithdrawnEvent.OutputObject
    >;

    "ReturnsDistributed(uint256,uint256)": TypedContractEvent<
      ReturnsDistributedEvent.InputTuple,
      ReturnsDistributedEvent.OutputTuple,
      ReturnsDistributedEvent.OutputObject
    >;
    ReturnsDistributed: TypedContractEvent<
      ReturnsDistributedEvent.InputTuple,
      ReturnsDistributedEvent.OutputTuple,
      ReturnsDistributedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
