/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IComplianceModule } from "./IComplianceModule";
export type { IInvestmentPool } from "./IInvestmentPool";
export type { IPropertyOracle } from "./IPropertyOracle";
