/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPropertyOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchUpdateValues"
      | "batchVerifyProperties"
      | "deactivateProperty"
      | "getAllProperties"
      | "getOwnerProperties"
      | "getProperty"
      | "getPropertyCount"
      | "getPropertyHistory"
      | "getVerifiedPropertyCount"
      | "isPropertyVerified"
      | "isValueCurrent"
      | "pause"
      | "reactivateProperty"
      | "recordInspection"
      | "registerProperty"
      | "transferOwnership"
      | "unpause"
      | "updatePropertyValue"
      | "verifyProperty"
      | "verifyPropertyOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PropertyInspected"
      | "PropertyRegistered"
      | "PropertyValueUpdated"
      | "PropertyVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchUpdateValues",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchVerifyProperties",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateProperty",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProperties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerProperties",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getProperty", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getPropertyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPropertyHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiedPropertyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPropertyVerified",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isValueCurrent",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateProperty",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordInspection",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProperty",
    values: [string, string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updatePropertyValue",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProperty",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPropertyOwnership",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchUpdateValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchVerifyProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropertyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropertyHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiedPropertyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPropertyVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValueCurrent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordInspection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePropertyValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPropertyOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    propertyId: string,
    oldOwner: AddressLike,
    newOwner: AddressLike
  ];
  export type OutputTuple = [
    propertyId: string,
    oldOwner: string,
    newOwner: string
  ];
  export interface OutputObject {
    propertyId: string;
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyInspectedEvent {
  export type InputTuple = [
    propertyId: string,
    inspector: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    inspector: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    inspector: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyRegisteredEvent {
  export type InputTuple = [
    propertyId: string,
    owner: AddressLike,
    marketValue: BigNumberish,
    propertyType: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    owner: string,
    marketValue: bigint,
    propertyType: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    owner: string;
    marketValue: bigint;
    propertyType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyValueUpdatedEvent {
  export type InputTuple = [
    propertyId: string,
    oldValue: BigNumberish,
    newValue: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    oldValue: bigint,
    newValue: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    oldValue: bigint;
    newValue: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyVerifiedEvent {
  export type InputTuple = [
    propertyId: string,
    verifier: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    verifier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    verifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPropertyOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IPropertyOracle;
  waitForDeployment(): Promise<this>;

  interface: IPropertyOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchUpdateValues: TypedContractMethod<
    [propertyIds: string[], newValues: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchVerifyProperties: TypedContractMethod<
    [propertyIds: string[]],
    [void],
    "nonpayable"
  >;

  deactivateProperty: TypedContractMethod<
    [propertyId: string],
    [void],
    "nonpayable"
  >;

  getAllProperties: TypedContractMethod<[], [string[]], "view">;

  getOwnerProperties: TypedContractMethod<
    [owner: AddressLike],
    [string[]],
    "view"
  >;

  getProperty: TypedContractMethod<
    [propertyId: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        _propertyId: string;
        fullAddress: string;
        owner: string;
        marketValue: bigint;
        lastValuation: bigint;
        isVerified: boolean;
        isActive: boolean;
        lastInspection: bigint;
        propertyType: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  getPropertyCount: TypedContractMethod<[], [bigint], "view">;

  getPropertyHistory: TypedContractMethod<
    [propertyId: string],
    [string[]],
    "view"
  >;

  getVerifiedPropertyCount: TypedContractMethod<[], [bigint], "view">;

  isPropertyVerified: TypedContractMethod<
    [propertyId: string],
    [boolean],
    "view"
  >;

  isValueCurrent: TypedContractMethod<[propertyId: string], [boolean], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  reactivateProperty: TypedContractMethod<
    [propertyId: string],
    [void],
    "nonpayable"
  >;

  recordInspection: TypedContractMethod<
    [propertyId: string],
    [void],
    "nonpayable"
  >;

  registerProperty: TypedContractMethod<
    [
      propertyId: string,
      fullAddress: string,
      owner: AddressLike,
      marketValue: BigNumberish,
      propertyType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [propertyId: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updatePropertyValue: TypedContractMethod<
    [propertyId: string, newValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyProperty: TypedContractMethod<
    [propertyId: string],
    [void],
    "nonpayable"
  >;

  verifyPropertyOwnership: TypedContractMethod<
    [propertyId: string, owner: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchUpdateValues"
  ): TypedContractMethod<
    [propertyIds: string[], newValues: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchVerifyProperties"
  ): TypedContractMethod<[propertyIds: string[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateProperty"
  ): TypedContractMethod<[propertyId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllProperties"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getOwnerProperties"
  ): TypedContractMethod<[owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProperty"
  ): TypedContractMethod<
    [propertyId: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        _propertyId: string;
        fullAddress: string;
        owner: string;
        marketValue: bigint;
        lastValuation: bigint;
        isVerified: boolean;
        isActive: boolean;
        lastInspection: bigint;
        propertyType: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPropertyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPropertyHistory"
  ): TypedContractMethod<[propertyId: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVerifiedPropertyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPropertyVerified"
  ): TypedContractMethod<[propertyId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValueCurrent"
  ): TypedContractMethod<[propertyId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reactivateProperty"
  ): TypedContractMethod<[propertyId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordInspection"
  ): TypedContractMethod<[propertyId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerProperty"
  ): TypedContractMethod<
    [
      propertyId: string,
      fullAddress: string,
      owner: AddressLike,
      marketValue: BigNumberish,
      propertyType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [propertyId: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePropertyValue"
  ): TypedContractMethod<
    [propertyId: string, newValue: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyProperty"
  ): TypedContractMethod<[propertyId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyPropertyOwnership"
  ): TypedContractMethod<
    [propertyId: string, owner: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyInspected"
  ): TypedContractEvent<
    PropertyInspectedEvent.InputTuple,
    PropertyInspectedEvent.OutputTuple,
    PropertyInspectedEvent.OutputObject
  >;
  getEvent(
    key: "PropertyRegistered"
  ): TypedContractEvent<
    PropertyRegisteredEvent.InputTuple,
    PropertyRegisteredEvent.OutputTuple,
    PropertyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyValueUpdated"
  ): TypedContractEvent<
    PropertyValueUpdatedEvent.InputTuple,
    PropertyValueUpdatedEvent.OutputTuple,
    PropertyValueUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PropertyVerified"
  ): TypedContractEvent<
    PropertyVerifiedEvent.InputTuple,
    PropertyVerifiedEvent.OutputTuple,
    PropertyVerifiedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(string,address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PropertyInspected(string,address,uint256)": TypedContractEvent<
      PropertyInspectedEvent.InputTuple,
      PropertyInspectedEvent.OutputTuple,
      PropertyInspectedEvent.OutputObject
    >;
    PropertyInspected: TypedContractEvent<
      PropertyInspectedEvent.InputTuple,
      PropertyInspectedEvent.OutputTuple,
      PropertyInspectedEvent.OutputObject
    >;

    "PropertyRegistered(string,address,uint256,uint8)": TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;
    PropertyRegistered: TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;

    "PropertyValueUpdated(string,uint256,uint256,uint256)": TypedContractEvent<
      PropertyValueUpdatedEvent.InputTuple,
      PropertyValueUpdatedEvent.OutputTuple,
      PropertyValueUpdatedEvent.OutputObject
    >;
    PropertyValueUpdated: TypedContractEvent<
      PropertyValueUpdatedEvent.InputTuple,
      PropertyValueUpdatedEvent.OutputTuple,
      PropertyValueUpdatedEvent.OutputObject
    >;

    "PropertyVerified(string,address,uint256)": TypedContractEvent<
      PropertyVerifiedEvent.InputTuple,
      PropertyVerifiedEvent.OutputTuple,
      PropertyVerifiedEvent.OutputObject
    >;
    PropertyVerified: TypedContractEvent<
      PropertyVerifiedEvent.InputTuple,
      PropertyVerifiedEvent.OutputTuple,
      PropertyVerifiedEvent.OutputObject
    >;
  };
}
