/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PythOracle {
  export type PropertyDataStruct = {
    propertyId: string;
    fullAddress: string;
    owner: AddressLike;
    marketValue: BigNumberish;
    lastValuation: BigNumberish;
    isVerified: boolean;
    isActive: boolean;
    lastInspection: BigNumberish;
    propertyType: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
    pythValidationTimestamp: BigNumberish;
  };

  export type PropertyDataStructOutput = [
    propertyId: string,
    fullAddress: string,
    owner: string,
    marketValue: bigint,
    lastValuation: bigint,
    isVerified: boolean,
    isActive: boolean,
    lastInspection: bigint,
    propertyType: bigint,
    createdAt: bigint,
    updatedAt: bigint,
    pythValidationTimestamp: bigint
  ] & {
    propertyId: string;
    fullAddress: string;
    owner: string;
    marketValue: bigint;
    lastValuation: bigint;
    isVerified: boolean;
    isActive: boolean;
    lastInspection: bigint;
    propertyType: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    pythValidationTimestamp: bigint;
  };
}

export interface PythOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "CONFIDENCE_THRESHOLD"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_PROPERTY_VALUE"
      | "MIN_PROPERTY_VALUE"
      | "ORACLE_ROLE"
      | "PRICE_DEVIATION_THRESHOLD"
      | "PRICE_VALIDATION_THRESHOLD"
      | "STALENESS_THRESHOLD"
      | "VALUATION_VALIDITY_PERIOD"
      | "VERIFICATION_VALIDITY_PERIOD"
      | "VERIFIER_ROLE"
      | "allPropertyIds"
      | "batchUpdateValuesWithPyth"
      | "getAllPropertyIds"
      | "getKrwUsdPrice"
      | "getOwnerProperties"
      | "getProperty"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "ownerProperties"
      | "pause"
      | "paused"
      | "properties"
      | "propertyHistory"
      | "registerProperty"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "unpause"
      | "validatePropertyValueWithPyth"
      | "verifyProperty"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OraclePaused"
      | "OracleUnpaused"
      | "Paused"
      | "PropertyRegistered"
      | "PropertyValueUpdated"
      | "PropertyVerified"
      | "PythPriceUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFIDENCE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PROPERTY_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PROPERTY_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_DEVIATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_VALIDATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STALENESS_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALUATION_VALIDITY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFICATION_VALIDITY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allPropertyIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateValuesWithPyth",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPropertyIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getKrwUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerProperties",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getProperty", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerProperties",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "properties", values: [string]): string;
  encodeFunctionData(
    functionFragment: "propertyHistory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProperty",
    values: [string, string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validatePropertyValueWithPyth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProperty",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CONFIDENCE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PROPERTY_VALUE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PROPERTY_VALUE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_DEVIATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_VALIDATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STALENESS_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALUATION_VALIDITY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFICATION_VALIDITY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allPropertyIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateValuesWithPyth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPropertyIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKrwUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "propertyHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validatePropertyValueWithPyth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProperty",
    data: BytesLike
  ): Result;
}

export namespace OraclePausedEvent {
  export type InputTuple = [admin: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [admin: string, timestamp: bigint];
  export interface OutputObject {
    admin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUnpausedEvent {
  export type InputTuple = [admin: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [admin: string, timestamp: bigint];
  export interface OutputObject {
    admin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyRegisteredEvent {
  export type InputTuple = [
    propertyId: string,
    owner: AddressLike,
    marketValue: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    owner: string,
    marketValue: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    owner: string;
    marketValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyValueUpdatedEvent {
  export type InputTuple = [
    propertyId: string,
    oldValue: BigNumberish,
    newValue: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    oldValue: bigint,
    newValue: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    oldValue: bigint;
    newValue: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyVerifiedEvent {
  export type InputTuple = [propertyId: string, timestamp: BigNumberish];
  export type OutputTuple = [propertyId: string, timestamp: bigint];
  export interface OutputObject {
    propertyId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PythPriceUpdatedEvent {
  export type InputTuple = [
    priceId: BytesLike,
    price: BigNumberish,
    timestamp: BigNumberish,
    confidence: BigNumberish
  ];
  export type OutputTuple = [
    priceId: string,
    price: bigint,
    timestamp: bigint,
    confidence: bigint
  ];
  export interface OutputObject {
    priceId: string;
    price: bigint;
    timestamp: bigint;
    confidence: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PythOracle extends BaseContract {
  connect(runner?: ContractRunner | null): PythOracle;
  waitForDeployment(): Promise<this>;

  interface: PythOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  CONFIDENCE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_PROPERTY_VALUE: TypedContractMethod<[], [bigint], "view">;

  MIN_PROPERTY_VALUE: TypedContractMethod<[], [bigint], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  PRICE_DEVIATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  PRICE_VALIDATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  STALENESS_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  VALUATION_VALIDITY_PERIOD: TypedContractMethod<[], [bigint], "view">;

  VERIFICATION_VALIDITY_PERIOD: TypedContractMethod<[], [bigint], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  allPropertyIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  batchUpdateValuesWithPyth: TypedContractMethod<
    [propertyIds: string[], newValues: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getAllPropertyIds: TypedContractMethod<[], [string[]], "view">;

  getKrwUsdPrice: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        confidence: bigint;
      }
    ],
    "view"
  >;

  getOwnerProperties: TypedContractMethod<
    [owner: AddressLike],
    [string[]],
    "view"
  >;

  getProperty: TypedContractMethod<
    [propertyId: string],
    [PythOracle.PropertyDataStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  ownerProperties: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  properties: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        propertyId: string;
        fullAddress: string;
        owner: string;
        marketValue: bigint;
        lastValuation: bigint;
        isVerified: boolean;
        isActive: boolean;
        lastInspection: bigint;
        propertyType: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        pythValidationTimestamp: bigint;
      }
    ],
    "view"
  >;

  propertyHistory: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  registerProperty: TypedContractMethod<
    [
      propertyId: string,
      fullAddress: string,
      owner: AddressLike,
      marketValue: BigNumberish,
      propertyType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  validatePropertyValueWithPyth: TypedContractMethod<
    [propertyValueKrw: BigNumberish],
    [boolean],
    "view"
  >;

  verifyProperty: TypedContractMethod<
    [propertyId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CONFIDENCE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_PROPERTY_VALUE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PROPERTY_VALUE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRICE_DEVIATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_VALIDATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STALENESS_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VALUATION_VALIDITY_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFICATION_VALIDITY_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allPropertyIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "batchUpdateValuesWithPyth"
  ): TypedContractMethod<
    [propertyIds: string[], newValues: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllPropertyIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getKrwUsdPrice"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        confidence: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerProperties"
  ): TypedContractMethod<[owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProperty"
  ): TypedContractMethod<
    [propertyId: string],
    [PythOracle.PropertyDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownerProperties"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "properties"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        propertyId: string;
        fullAddress: string;
        owner: string;
        marketValue: bigint;
        lastValuation: bigint;
        isVerified: boolean;
        isActive: boolean;
        lastInspection: bigint;
        propertyType: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        pythValidationTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "propertyHistory"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerProperty"
  ): TypedContractMethod<
    [
      propertyId: string,
      fullAddress: string,
      owner: AddressLike,
      marketValue: BigNumberish,
      propertyType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validatePropertyValueWithPyth"
  ): TypedContractMethod<[propertyValueKrw: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyProperty"
  ): TypedContractMethod<[propertyId: string], [void], "nonpayable">;

  getEvent(
    key: "OraclePaused"
  ): TypedContractEvent<
    OraclePausedEvent.InputTuple,
    OraclePausedEvent.OutputTuple,
    OraclePausedEvent.OutputObject
  >;
  getEvent(
    key: "OracleUnpaused"
  ): TypedContractEvent<
    OracleUnpausedEvent.InputTuple,
    OracleUnpausedEvent.OutputTuple,
    OracleUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PropertyRegistered"
  ): TypedContractEvent<
    PropertyRegisteredEvent.InputTuple,
    PropertyRegisteredEvent.OutputTuple,
    PropertyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyValueUpdated"
  ): TypedContractEvent<
    PropertyValueUpdatedEvent.InputTuple,
    PropertyValueUpdatedEvent.OutputTuple,
    PropertyValueUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PropertyVerified"
  ): TypedContractEvent<
    PropertyVerifiedEvent.InputTuple,
    PropertyVerifiedEvent.OutputTuple,
    PropertyVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "PythPriceUpdated"
  ): TypedContractEvent<
    PythPriceUpdatedEvent.InputTuple,
    PythPriceUpdatedEvent.OutputTuple,
    PythPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OraclePaused(address,uint256)": TypedContractEvent<
      OraclePausedEvent.InputTuple,
      OraclePausedEvent.OutputTuple,
      OraclePausedEvent.OutputObject
    >;
    OraclePaused: TypedContractEvent<
      OraclePausedEvent.InputTuple,
      OraclePausedEvent.OutputTuple,
      OraclePausedEvent.OutputObject
    >;

    "OracleUnpaused(address,uint256)": TypedContractEvent<
      OracleUnpausedEvent.InputTuple,
      OracleUnpausedEvent.OutputTuple,
      OracleUnpausedEvent.OutputObject
    >;
    OracleUnpaused: TypedContractEvent<
      OracleUnpausedEvent.InputTuple,
      OracleUnpausedEvent.OutputTuple,
      OracleUnpausedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PropertyRegistered(string,address,uint256)": TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;
    PropertyRegistered: TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;

    "PropertyValueUpdated(string,uint256,uint256,uint256)": TypedContractEvent<
      PropertyValueUpdatedEvent.InputTuple,
      PropertyValueUpdatedEvent.OutputTuple,
      PropertyValueUpdatedEvent.OutputObject
    >;
    PropertyValueUpdated: TypedContractEvent<
      PropertyValueUpdatedEvent.InputTuple,
      PropertyValueUpdatedEvent.OutputTuple,
      PropertyValueUpdatedEvent.OutputObject
    >;

    "PropertyVerified(string,uint256)": TypedContractEvent<
      PropertyVerifiedEvent.InputTuple,
      PropertyVerifiedEvent.OutputTuple,
      PropertyVerifiedEvent.OutputObject
    >;
    PropertyVerified: TypedContractEvent<
      PropertyVerifiedEvent.InputTuple,
      PropertyVerifiedEvent.OutputTuple,
      PropertyVerifiedEvent.OutputObject
    >;

    "PythPriceUpdated(bytes32,int64,uint64,uint64)": TypedContractEvent<
      PythPriceUpdatedEvent.InputTuple,
      PythPriceUpdatedEvent.OutputTuple,
      PythPriceUpdatedEvent.OutputObject
    >;
    PythPriceUpdated: TypedContractEvent<
      PythPriceUpdatedEvent.InputTuple,
      PythPriceUpdatedEvent.OutputTuple,
      PythPriceUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
